name:            SpigCoot
main:            com.coot.SpigCoot
version:         1.0
api-version: 1.16
commands:
   bank:
      description: View bank balance
   warp:
      description: Warp somewhere.
   setWarp:
      description: Create a warp.
   remWarp:
      description: Remove a warp.
   tpa:
      description: Teleport request.
   tpaccept:
      description: Accept a teleport request.